language: ruby
rvm:
- 2.2
branches:
  only:
  - master
  - live
install:
- bundle install
cache:
  bundler: true
script:
- jekyll build
deploy:
- provider: s3
  access_key_id:
    secure: g+2PNrmWiETlQzITk6s0NbnsEXHye/MrVrGkHPd1AoDSEZ95P9lgujK0GuNyRNiXqIWC4HdgO0crGzqyhVhTpdZodVLCpwqzxIbE7sxCVVrAH5EZPyFHNj6IGogfO4PH8mMt2XmOe5QvjVH5Nzh0cg5PUU86keSR4+p3bU/erWAZpFpE0GirB3IM3ILr1PspOwVm25+F8ITti/32rxusW0I2gVyx6Mrzq2n2fqf0OSittkdCPDUYZUoXjLr04C0HTRIG1ctzsPrW2Q0qsYNN1Q4H7395Herj3z0bddr+ruKDpNGoIL++w2RGPk/etC1yUAAAP9E8PPYLuQHRJ+0Iy0l7qXvU+USQ3k1V6LnQoL9YJtmMhqzVo8+x/B5NlRxld8TmOqIUV5j/B9JYXIyr7pyUiq1a2tM+kY0Ys0eLiMAhEclXgCdDIIaKAx09LYYuxHafJwWm1xNb/G8Kdl3o3eKk/eTb3HLwnzqCXT6IF4J+E48DKWrdFmpKTZhroOAiE0pwxxiZ12ziZ6uQHu/QfYeUDEDHhFVT1al9xiLUymihtT02mvRdxYZFdo+ZaZulLWU+rK509qJKEjcvuH7sldBpgNEFetI/MTQNq3gKNkion5+/tv/f4UP+pNFzupeVhsaVVxp8IzbhchKRr+qkdLNwpgY61OYUUXJOXPLcVCE=
  secret_access_key:
    secure: tLwCAprjeSpZ2llOMd0KyOrmTsWaKmGL2SQk2Sqr68yy/a0H1ZjTDhhOkmNzoH/znAekgCczz/3b+64Qsy5Qfzz5rSp8Kq56Urmre9Qo0UpxWSc13Xa4KcPB4+ANjt8qYPHAfC4vYhEs3tQ/E35tf8iEcxbHDmw1Nr574s7O4fxNuxAYvthw22Dnz4qAVn9Zbl6UIQdU0oF6DDkSOOnHNEIZEmR8gwPi640I2p+ZSdGbsWnR4Xe9vh6PxhjTLVMJKKyuG4Y0gkp/SGudTwEHtm/8Pbo8kFUOnQpIeE2gBhXLuE9bVr0E5hg8cRgTHlaALgPdyxfq3VTP52wp/dQ2j0aS9uBWA5/Jx23cvI3TDYbzQxy2/nH3jg6ZXoysQHxM5PwkIaZajAoZ/EtVgpsHq0E7gHpgRr7lj+WwG4UQz8UiDz/kFy1LZ0ClkrCKjoW+FgcyodjwjFUUQTwdu0yH/KJUcd/blAZWwUj+iP4+hp/9NYFXDPbkuncjnNr97nBzjF81Y8vHxzz4lRbVAqZsj38bl4XBjqFJm+rVt8xSBHuefrX2jmVvOtaaePi6V0B0vMMcbFUI2Br95oS2AbKRbpNr4e5vlcLW7xFStbBRgAA1fqXDncomxpfO+iYAW9hpo3dVlKFxqCErz7J+jn2zEfehXe86QpJghYzr5SP5fQA=
  bucket: aws-website-stageatkinsdigital-13n6k
  skip_cleanup: true
  local_dir: build
  region: us-east-1
  on:
    branch: master
- provider: s3
  access_key_id:
    secure: g+2PNrmWiETlQzITk6s0NbnsEXHye/MrVrGkHPd1AoDSEZ95P9lgujK0GuNyRNiXqIWC4HdgO0crGzqyhVhTpdZodVLCpwqzxIbE7sxCVVrAH5EZPyFHNj6IGogfO4PH8mMt2XmOe5QvjVH5Nzh0cg5PUU86keSR4+p3bU/erWAZpFpE0GirB3IM3ILr1PspOwVm25+F8ITti/32rxusW0I2gVyx6Mrzq2n2fqf0OSittkdCPDUYZUoXjLr04C0HTRIG1ctzsPrW2Q0qsYNN1Q4H7395Herj3z0bddr+ruKDpNGoIL++w2RGPk/etC1yUAAAP9E8PPYLuQHRJ+0Iy0l7qXvU+USQ3k1V6LnQoL9YJtmMhqzVo8+x/B5NlRxld8TmOqIUV5j/B9JYXIyr7pyUiq1a2tM+kY0Ys0eLiMAhEclXgCdDIIaKAx09LYYuxHafJwWm1xNb/G8Kdl3o3eKk/eTb3HLwnzqCXT6IF4J+E48DKWrdFmpKTZhroOAiE0pwxxiZ12ziZ6uQHu/QfYeUDEDHhFVT1al9xiLUymihtT02mvRdxYZFdo+ZaZulLWU+rK509qJKEjcvuH7sldBpgNEFetI/MTQNq3gKNkion5+/tv/f4UP+pNFzupeVhsaVVxp8IzbhchKRr+qkdLNwpgY61OYUUXJOXPLcVCE=
  secret_access_key:
    secure: tLwCAprjeSpZ2llOMd0KyOrmTsWaKmGL2SQk2Sqr68yy/a0H1ZjTDhhOkmNzoH/znAekgCczz/3b+64Qsy5Qfzz5rSp8Kq56Urmre9Qo0UpxWSc13Xa4KcPB4+ANjt8qYPHAfC4vYhEs3tQ/E35tf8iEcxbHDmw1Nr574s7O4fxNuxAYvthw22Dnz4qAVn9Zbl6UIQdU0oF6DDkSOOnHNEIZEmR8gwPi640I2p+ZSdGbsWnR4Xe9vh6PxhjTLVMJKKyuG4Y0gkp/SGudTwEHtm/8Pbo8kFUOnQpIeE2gBhXLuE9bVr0E5hg8cRgTHlaALgPdyxfq3VTP52wp/dQ2j0aS9uBWA5/Jx23cvI3TDYbzQxy2/nH3jg6ZXoysQHxM5PwkIaZajAoZ/EtVgpsHq0E7gHpgRr7lj+WwG4UQz8UiDz/kFy1LZ0ClkrCKjoW+FgcyodjwjFUUQTwdu0yH/KJUcd/blAZWwUj+iP4+hp/9NYFXDPbkuncjnNr97nBzjF81Y8vHxzz4lRbVAqZsj38bl4XBjqFJm+rVt8xSBHuefrX2jmVvOtaaePi6V0B0vMMcbFUI2Br95oS2AbKRbpNr4e5vlcLW7xFStbBRgAA1fqXDncomxpfO+iYAW9hpo3dVlKFxqCErz7J+jn2zEfehXe86QpJghYzr5SP5fQA=
  bucket: aws-website-atkinsdigital-a04qb
  skip_cleanup: true
  local_dir: build
  region: us-east-1
  on:
    branch: live
