language: ruby
rvm:
  - 2.2
branches:
  only:
    - master
    - live
env:
  - "rack=master"
install:
  - bundle install
cache:
  bundler: true
deploy:
  provider: s3
  access_key_id:
    secure: getdpSzJeQRYyI44jvW1jpSNnR3+cQV6clo6b8Gj8enCUFrFvOf11Hl8uVvFrOYX85J90NQHdtK8p8NvOfsKcnj8Zq/LYLmYRkAGWZzEFhW+Lp01Pe9UWyX+X9vRhk/h1dKuf95BoyyMAQuA+HBBkI3HXWppafWUkLSygXQZguIoy3LlXXTWA2tK4Dqm6YwWeJhvTDnmylIKs5p7erOOarxg54+kG/A4D85VxVROAhgLF7cgIYXrVdmqO+7AO147Gv8M4qpikrZDpG1DE/cAc4088nt7MtczE8O7IX0utd+rQp2GbyBdIL3HraZZarQ8IbcV+IWp27/AmMCGfabZ2wbtBY3ztv/aWDUFVQ/CbpmjHfxi44y6Vg2kSmaAusRRSlSZQ4yfVKUEbXS828TpMaKy+1n7xjxLq2Pgs56ceSoYMJWx4Oxja2dUyk6LRWy2MtOqdpqWXQEgir27M76/0hgZgLTO6dFGy0hCTRasIejVr6ihVEteXVkiCiNLOYTEHOZ1wul1cJVtcOzyO5/xC+1smLT107CRn/gij0kKn0Fb/hn5S5Sxq2dZY7TIEgRTVOBw3sBGak8Rbq9Wh9vS2x/Fk07w1eX59FQG+6sM2pseZ01n7bFPT6eCQOaRZ+5ly9jvU4Dsxig/1oRAwAMBhLBrar1ZE0/y0bjuuO/znjM=
  secret_access_key:
    secure: p7qerV3WjTqo2VGpkFTI5mCob8zf1ToyYZnWgwyVVyCes0CmeycKEdaVzhvoCxveN0t1v6+UgtCxKES9W19BnbIV6b36fbow+yRXAbwl/B8D9HMTuQAJOZPNxtZpr1dbhag8tTQDd0aUggwU7LoRM7vxoNd6+ieznl8k0RdikGNHujsv3LXeeQT5hMXqie0Vox4mrwZ7B7RaSBpDG8T0+OK+Wy3VziiO2HE/RmGQqXJ6dKzXuU42Op8SP1Ar8G5HaCFwhVUK9UqmN/5/1aJNZdjkWIAuv3nhV+hnRhBJFrpcdafLTo4DKKuJRyrTbYHse4FlQLqJWuRboz1ZmoQZneP6Ms45Z01VMKjjUe32ul9RP8ckf/87wwV3f9vKemIZfBIPjOzA+zoGO224ZKqsN1Qay9y6HKH9fTNihzoPPyjn9A/iYoGgT8jFwG9sz0eTpEtJt7Jm8AYv72tnsGPraBG5jN1u6C6/ecQgtq0FsA7zouLoUu0wsjBAEryfJRPTPp8pnXSeuhs78g9eZ9gAJIYvaSrxrB2LQKrY3mc06IyHbzcOFMMdkXMy5/hm6XYvO9beZNT790eEJFjZoJ64xzc4DRNrTEHwcSq/T5eNHAKqDAG35aWup4CyqsNq4OJlJoymmbXDOEPdVEUCPpFcHLJULtyHQKutmLX/cn0hIZ4=
  bucket: stage.atkins.digital
